#!/bin/bash
# Regenerate app_decks.md5 — the list of decks the APPS ship, which is the only thing this repo may serve.
#
# ONE update path: Server regenerates it from the iOS release branch that ships the decks, commits it in
# the same PR as any deck change here, and the deck-parity check verifies the PR against it.
# (Android's bundled decks are held byte-identical to iOS by the apps' own md5 parity test.)
#
#   usage:  tools/regen_app_decks_md5.sh <path-to-forbidden-ios-checkout> <ref>
#   e.g.    tools/regen_app_decks_md5.sh ../ios origin/release/2.9.0
set -euo pipefail
IOS="${1:?path to the forbidden-ios checkout}"; REF="${2:?git ref of the shipping release, e.g. origin/release/2.9.0}"
DIR="Taboo/Resources/Data"
SHA=$(git -C "$IOS" rev-parse --short "$REF")
OUT="$(cd "$(dirname "$0")/.." && pwd)/app_decks.md5"
files=$(git -C "$IOS" ls-tree --name-only "$REF" "$DIR/" | sed "s#^$DIR/##" | grep -E '^game_data_[a-z]+\.json$')
[ -n "$files" ] || { echo "no game_data_*.json under $DIR at $REF" >&2; exit 1; }
md5of() { git -C "$IOS" show "$REF:$DIR/$1" | python3 -c 'import hashlib,sys;print(hashlib.md5(sys.stdin.buffer.read()).hexdigest())'; }
tmp=$(mktemp)
{
  echo "# App-bundled decks — generated by tools/regen_app_decks_md5.sh from forbidden-ios $REF @ $SHA ($DIR)."
  echo "# Do not edit by hand. game_data.json is the legacy (v2.0.0) alias of the English deck."
  for f in $files; do
    printf '%s  %s\n' "$(md5of "$f")" "$f"
  done
  printf '%s  %s\n' "$(md5of game_data_en.json)" "game_data.json"
} > "$tmp"
mv "$tmp" "$OUT"
echo "wrote $OUT ($(grep -vc '^#' "$OUT") decks, from $REF @ $SHA)"
